#!/bin/bash
#
#aja järgi tervitamine
#
echo -n "Sisesta kellaaeg täistunndides: "
read aeg
#kontrollimine
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
	echo "Tere hommikust, $(whoami)!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
	echo "Tere päevast, $(whoami)!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
	echo "Tere õhtust, $(whoami)!"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
	echo "Head ööd, $(whoami)!"
else
	echo "Vale sisend"
fi
#skripti lõpp
