#!/bin/bash
#
#reisi korraldamine
#
#
echo -n "Sisesta reisijate arv: "
read reisijad
#kohtade andmed bussis
echo -n "Sisestage kohtade arv bussis: "
read kohad
#mitu bussi täidetakse
busside_arv=`expr $reisijad / $kohad`
#mitu kohta jääb puudu
puudu=`expr $reisijad % $kohad`
if [ $puudu -eq 0 ]
	then echo "Kokku on vaja $busside_arv bussis"
	else echo "Kokku on vaja `expr $busside_arv + 1` bussi"
fi
