#!/bin/bash
#
echo -n "Sisesta kuu number (1-12): "
read kuu

case $kuu in
	"1") echo "See kuu on jaanuar.";;
	"2") echo "See kuu on veebruar.";;
	"3") echo "See kuu on märts.";;
	"4") echo "See kuu on aprill.";;
	"5") echo "See kuu on mai.";;
	"6") echo "See kuu on juuni.";;
	"7") echo "See kuu on juuli.";;
	"8") echo "See kuu on august.";;
	"9") echo "See kuu on september.";;
	"10") echo "See kuu on oktoober.";;
	"11") echo "See kuu on november.";;
	"12") echo "See kuu on detsember.";;
	*) echo "Sellist kuud pole või sisend on vigane, vabandame.";;

esac
