#!/bin/bash
#
#kasutaja tervitus
#
#skripti algus
#
echo -n "Sisesta oma ees- ja perenimi: "
read eesnimi perenimi
echo "Sinu eesnimi on $eesnimi ja perenimi on $perenimi"
echo Tere tulemast $eesnimi $perenimi!
#
#skripti lõpp
