#!/bin/bash
#
echo -n "Sisesta ridade arv: "
read rida
echo -n "Sisesta tarnide arv reas: "
read tarn
	for ((i = 1; i <= $rida; i++ ))
	do
		if [ $i = 1 ] || [ $i = $rida ]
		then
		echo -n ""
			for (( l = 1; l <= $tarn; l++ ))
			do
			echo -n "*"
			done
		echo ""
		else
		for ((j = 1; j <= 1; j++))
		do
			echo -n "*"
		done
		for (( k = 1; k <= $tarn; k++))
		do
			echo -n " "
		done
             echo "*"
fi
done
