#!/bin/bash
#
echo -n "Sisesta ridade arv: "
read rida
echo -n "Sissta tarnide arv reas: "
read tarn
	for ((i = 1; i <= $rida; i++ ))
	do
		for ((j = 1; j <= 1; j++))
		do
			echo -n "$i.*"
		done
		for (( k = 1; k <= $tarn; k++))
		do
			echo -n " "
		done
             echo "*"
          done
